# =============================================================================
# Environmental, ordination, PERMANOVA, and network analyses
#
# Purpose:
#   Join leaf/environmental metadata to a phyloseq object, prepare community
#   and environmental data, perform RDA, PCoA, dbRDA, PERMANOVA, dispersion
#   tests, pairwise comparisons.
#
# Required objects before running this script:
#   ps4         - phyloseq object containing abundance, taxonomy, sample data,
#                 and a phylogenetic tree
#   samples.out - sample identifiers used when expanding plot-level metadata
#   site        - site identifiers corresponding to samples.out
#   numenv      - numeric environmental data frame used in early filtering
#   facenv      - categorical environmental data frame used in early filtering
#   comb.pcoa   - combined PCoA data used in plotting, unless generated by the
#                 currently commented code
#   pCoA.scores - ordination scores used near the end of the script
#   yourData    - object used in the final tax_fix() example
#
# Input files expected in the repository:
#   data/Blatt_umwelt_data.csv
#   data/ibf_env2.csv
#   data/ps4_ASV.csv
#   data/enviro_dat2.csv
#
# Optional input files referenced in commented code:
#   data/Baumarten_IBF.csv
#   data/shannon.csv
#
# Output files:
#   results/ps4_taxa.csv
#   results/enviro_dat.csv
#
# Local source packages expected when the installation lines are used:
#   packages/NetCoMi-1.1.0.tar.gz
#   packages/orca_1.1-1.tar.gz
#   packages/mixedCCA_1.6.2.tar.gz
#
# Run this script from the repository root or an RStudio project. Create the
# data/, results/, and packages/ directories before execution.
#
# For reproducibility:
#   - record package versions with renv::snapshot() or sessionInfo();
#   - set a fixed seed before permutation or stochastic procedures when exact
#     repeatability is required, for example set.seed(1234);
#   - ensure community and metadata tables have matching sample order and names;
#   - document the origin and preprocessing of objects not created here.
#
# The analysis commands, parameters, object names, and active workflow below
# are preserved. Only comments and computer-specific paths were changed.
# =============================================================================

# Load packages --------------------------------------------------------------
library(vegan)
library(phyloseq)
library(GUniFrac)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(microbiome)
library(microViz)
library(microeco)
library(file2meco)

# Import leaf and environmental metadata. The file must contain a Sample column
# matching sample names in ps4 and a plot column used below as row names.
blatt_umw<-read.csv("data/Blatt_umwelt_data.csv", header = TRUE)

# Join metadata to the phyloseq object by Sample.
# Verify the number of samples before and after the join to document exclusions.
phylo_blatt<-ps_join(ps4,blatt_umw,
  by = "Sample",
  match_sample_names = TRUE,
  keep_sample_name_col = TRUE,
  sample_name_natural_join = TRUE,
  type = "left",
  .keep_all_taxa = FALSE
)

summary(blatt_umw)
blatt_umw<-tibble::column_to_rownames(blatt_umw,"plot")

# Export the processed metadata table using a repository-relative path.
write.csv(blatt_umw, "results/ps4_taxa.csv")

num_blatt<-blatt_umw %>% select_if(is.numeric)

# Convert the phyloseq object to a microtable for analysis with microeco.
micro_blatt<-phyloseq2meco(phylo_blatt)


# Import plot-level environmental variables.
env<-read.csv("data/ibf_env2.csv", header = TRUE, sep=";")

env<-na.exclude(env)

num<-sapply(env, is.numeric)

# env2 contained only numeric variables; the corresponding code was deleted.


# Import the ASV abundance table and the table currently referenced as taxonomy.
# Confirm that row and column orientations match the phyloseq() constructor below.
otu<-read.csv("data/ps4_ASV.csv", header = TRUE, sep=",")
tax<-read.csv("results/ps4_taxa.csv", header=TRUE, sep = ",")

# Creation and manipulation of data frames

otu<-tibble::column_to_rownames(otu,"X")
otu<-otu %>%arrange(X)
numenv<-numenv %>% arrange(rownames)
numenv<-subset(numenv, select=-c(column2,column3))
numenv$RHJul<-NULL # Delete the RHJul column

# Remove complete plots/sites from the data frames.
numenv <- numenv[!grepl("TH2", rownames(numenv)), ]
otu <- otu[!grepl("TH2", rownames(otu)), ]
facenv <- facenv[!grepl("BY3", rownames(facenv)), ]
site <- site[!(site %in% c("BY2","BY3", "TH2"))]

psenv<- phyloseq(otu,tax,env)

#plot_heatmap(ps4, ps4@sam_data[["Site"]], title = "Vergleich der Mikrobiome zwischen den Standorten")


site_order <- sort(unique(sample_data(ps4)$site))
plot_heatmap(ps4, taxa.order = site_order)

# Expand plot-level environmental data to all sampled trees.
ftry<-data.frame(samples.out,site,env)
colnames(ftry)[colnames(ftry)=="site"] <- "plot"
ftry2<-merge(ftry,env,by ="plot")
ftry2<-ftry2%>% arrange(samples.out)
# ftry2 is the complete environmental data frame for all plots; do not modify it directly, only create derived objects.

colnames(otu)[colnames(otu)=="plot"] <- "samples.out"
bla<-merge(ftry2,otu, by = "samples.out")


otu<-tibble::column_to_rownames(otu,"X.NAME")
# Apply the Hellinger transformation to the abundance table.
otu.total<-  decostand(otu, method = "hellinger")

enviro<-tibble::column_to_rownames(ftry2,"samples.out")
write.csv(enviro, "results/enviro_dat.csv")
enviro.neu<-read.csv("data/enviro_dat2.csv", sep = ",")


numenv<-enviro.neu %>% select_if(is.numeric)
facenv<-enviro %>% select_if(is.character)
numenv<-as.data.frame.data.frame(numenv)
# Standardize numeric environmental variables to zero mean and unit variance.
env.z<-decostand(numenv, method = "standardize")
neuenv<-cbind(env.z, enviro$plot,enviro$bodentyp,enviro$hangrichtung)

logenvy<-log(numenv) 

numenv <- numenv[!(rownames(numenv) %in% c("TH1-01", "TH2-14","ST1-04","MV1-09","BB1-14","ST1-21","NI1-28","BY1-17","BB1-07","BY1-27")), ]
neuenv <- neuenv[!(rownames(neuenv) %in% c("TH1-01", "TH2-14","ST1-04","MV1-09","BB1-14","ST1-21","NI1-28","BY1-17","BB1-07","BY1-27")), ]
facenv <- facenv[!(rownames(facenv) %in% c("TH1-01", "TH2-14","ST1-04","MV1-09","BB1-14","ST1-21","NI1-28","BY1-17","BB1-07","BY1-27")), ]

##### Ordination analyses start here

# Run redundancy analysis using all available predictors in blatt_umw.
# Record the number of complete cases retained by na.omit.
rdares<-rda(otu ~  ., data=blatt_umw, na.action = na.omit)# Originally neuenv, numenv
summary(rdares)

fwd.sel<-ordiR2step(rda(otu~ 1,data=blatt_umw,na.action = na.omit),
                    scope = formula(rdares),
                    direction ="backward",
                    R2scope = FALSE,
                    pstep = 1000,
                    trace = TRUE)
fwd.sel$call

anova.cca(rdares,step=1000, by = "term")
ordiplot(rdares, scaling = 2, type = "text")

#ccares<-cca(otu.total ~ ., enviro, na.action = na.exclude)

###
# PCoA 
library(ecodist)
library(ape)
# Calculate Bray-Curtis dissimilarities among samples.
pcoa.otu<-vegdist(otu, method = "bray")# OTU distance matrix
##

pcoa.res<-cmdscale(pcoa.otu,k=2) #MDS/PCA
#pcoa.env<-vegdist(numenv, method = "bray", na.rm = TRUE)
#pcoa.res2<-cmdscale(pcoa.env,k=2)

# Convert the PCoA result to a data frame
pcoa_com <- as.data.frame(pcoa.res)
#env_data <- as.data.frame(pcoa.res2)
#comb.pcoa <- data.frame(OTU1 = pcoa.res[, 1], OTU2 = pcoa.res[, 2], Env1 = pcoa.res2[, 1], Env2 = pcoa.res2[, 2])
plot(comb.pcoa)
biplot(pcoa_com)



#####
# PERMANOVA

# Test community differences with PERMANOVA.
# Report the permutation count and test multivariate dispersion alongside PERMANOVA.
perm.res<-adonis2(pcoa.otu~., data = facenv, method = "bray")
#shannon+ph+kationen.austauschkapazitaet+ca_vorrat+k_vorrat+mg_vorrat+n_vorrat+MAT+MAP+HHN+dBHD_ashes+ökoG+NA_vorrat+corg_vorrat
plot(perm.res)
perm.res

disp.perm<-betadisper(pcoa.otu,group = facenv$plot,type = c("centroid"))
permutest(disp.perm)
plot(disp.perm, hull=FALSE, ellipse=TRUE)
plot(disp.perm, hull=TRUE, ellipse=FALSE)
boxplot(disp.perm)

library(pairwiseAdonis)
pair.res<-pairwise.adonis2(pcoa.otu~plot,data = facenv, p.adjust.m='bonferroni')
pair.res
plot(pair.res)

# Create a scatterplot
ggplot(comb.pcoa, aes(x = OTU1, y = OTU2)) +
  geom_point() +
  labs(x = "PCoA Axis 1", y = "PCoA Axis 2") +
  ggtitle("PCoA Plot")


library(lme4)

hist(logenvy$Tjul)

glres<-glmer(pcoa.otu~.,data=numenv, family = "poisson")

pcres<-cmdscale(pCoA.scores,k=2)

#####
# Additional metadata manipulation

neuenv<-neuenv %>%
  rename("bodentyp"="enviro$bodentyp",
         "hangrichtung"="enviro$hangrichtung",
         "kat.austausch"="kationen.austauschkapazitaet")

numenv<-tibble::rownames_to_column(numenv,var="site") 
numenv<-tibble::column_to_rownames(numenv,var="site") 

bla<-c("BB1","BW1","BY1","HE1","MV1","NI1","SN1","ST1","TH1")
numenv$plot<-sub(paste("^(", paste(bla, collapse = "|"), ").*", sep = ""), "\\1", numenv$site)



